services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluetooth_monitor_backend
    image: bluetooth-monitor-backend
    ports:
      - "8080:8080"
    volumes:
      - /var/www:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bluetooth_monitor_db:3306/bluetooth_monitor?serverTimezone=Europe/Moscow
      SPRING_DATASOURCE_USERNAME: bluetooth_monitor_user
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: bluetooth_monitor_db
    restart: always
    environment:
      MYSQL_DATABASE: bluetooth_monitor
      MYSQL_USER: bluetooth_monitor_user
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=64M

volumes:
  mysql_data:
